---
title: "Data Science Resources"
subtitle: "A collection of useful, freely-available data science resources and links, curated by [Nicola Rennie](https://nrennie.rbind.io/)."
---

This resource list was last updated on `r format(Sys.time(), '%b %d, %Y')`. Want to add a resource? File an issue or edit the `resources.csv` file on [GitHub](https://github.com/nrennie/data-science-resources) and submit a PR.

```{r}
#| message: false
resources <- readr::read_csv("resources.csv") |>
  dplyr::mutate(
    LinkText = stringr::str_remove_all(Link, "https://|/$"),
    Link = glue::glue("<a href='{Link}' target = '_blank'>{LinkText}</a>")
  ) |>
  dplyr::select(-LinkText) |>
  dplyr::mutate(
    Category = stringr::str_replace_all(Category, ";", ", ")
  )
```

```{r}
#| message: false
library(htmltools)
filter_fct <- function(values, name) {
  tags$select(
    tags$option(value = "", "All"),
    purrr::map(unique(values), tags$option),
    onchange = glue::glue(
      "Reactable.setFilter(
        'resources-tbl',
        '{name}',
        event.target.value
      )"
    )
  )
}
```


```{r}
resources |>
  dplyr::arrange(Type, Title) |>
  reactable::reactable(
    columns = list(
      Type = reactable::colDef(
        name = "Type",
        filterInput = filter_fct,
        maxWidth = 180
      ),
      Link = reactable::colDef(
        html = TRUE
      ),
      Category = reactable::colDef(
        maxWidth = 180
      )
    ),
    searchable = TRUE,
    striped = TRUE,
    pagination = FALSE,
    elementId = "resources-tbl",
    filterable = TRUE,
    sortable = TRUE,
    showSortable = TRUE
  )
```

<br>

Links to external websites are provided for convenience and informational purposes only. We do not endorse, guarantee, or take responsibility for the accuracy, reliability, or content of any linked site.

